In [2]:
import numpy as np

In [7]:
my_list=[2,3,4,5]
arr=np.array(my_list)
arr

array([2, 3, 4, 5])

In [6]:
type(arr)

numpy.ndarray

In [8]:
arr.shape

(4,)

In [10]:
my_2d_list=[[1,2,3],[5,6,7]]
arr_2d=np.array(my_2d_list)
arr_2d

array([[1, 2, 3],
       [5, 6, 7]])

In [11]:
arr_2d.shape

(2, 3)

In [13]:
arr_2d.reshape(3,2)

array([[1, 2],
       [3, 5],
       [6, 7]])

In [17]:
arr=np.arange(0,5,step=0.5)
arr

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [18]:
#equally spaced
np.linspace(start=0,stop=50,num=10)

array([ 0.        ,  5.55555556, 11.11111111, 16.66666667, 22.22222222,
       27.77777778, 33.33333333, 38.88888889, 44.44444444, 50.        ])

In [19]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [20]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [26]:
np.eye(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [23]:
np.full((2,3),5)

array([[5, 5, 5],
       [5, 5, 5]])

In [27]:
np.random.rand(4)

array([0.99068264, 0.06997028, 0.53783628, 0.19113311])